### ISSUE TITLE
Failed to read "target os" value "OSAndroid"

### ISSUE THREAD

**Issue by yihuang** [zw3rk/ghc#1]
I'm following your tutorial to build ghc android cross compiler on mac, but i got this error, do you know what went wrong?

```
"inplace/bin/ghc-cabal" configure libraries/ghc-prim dist-install "" --with-ghc=...
Configuring ghc-prim-0.5.0.0...
ghc-cabal: '.../ghc/inplace/bin/ghc-stage1' exited with an
error:
Failed to read "target os" value "OSAndroid"
```

**Comment by yihuang** [comment]
I've fixed this by these changes:
```
diff --git a/compiler/utils/Platform.hs b/compiler/utils/Platform.hs
index 8cd1fa7..3f748d1 100644
--- a/compiler/utils/Platform.hs
+++ b/compiler/utils/Platform.hs
@@ -85,6 +85,7 @@ data OS
         | OSHaiku
         | OSQNXNTO
         | OSAIX
+        | OSAndroid
         deriving (Read, Show, Eq)

 -- | ARM Instruction Set Architecture, Extensions and ABI
@@ -128,6 +129,7 @@ osElfTarget OSDragonFly = True
 osElfTarget OSOpenBSD   = True
 osElfTarget OSNetBSD    = True
 osElfTarget OSSolaris2  = True
+osElfTarget OSAndroid   = True
 osElfTarget OSDarwin    = False
 osElfTarget OSMinGW32   = False
 osElfTarget OSKFreeBSD  = True
```

But i got new error now:
```
ld --sysroot=.../android-ndk-r10e/platforms/android-21/arch-arm -L.../android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9/ --sysroot=.../android-ndk-r10e/platforms/android-21/arch-arm -pie -X --eh-frame-hdr -m armelf_linux_eabi -dynamic-linker /system/bin/linker -o libraries/base/dist-install/build/GHC/Float.o -L... -z noexecstack --no-as-needed -r --build-id=none /var/folders/qm/6l66y_0n363brqwst97d129r0000gn/T/ghc23676_0/ghc_12.ldscript
ld: fatal error: -pie and -r are incompatible
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`armv7-linux-androideabi-clang' failed in phase `Linker'. (Exit code: 1)
make[1]: *** [libraries/base/dist-install/build/GHC/Float.o] Error 1
make: *** [all] Error 2
```

**Comment by yihuang** [comment]
It seems I was running boot on wrong branch, I'll do it all over again, and see what it ends.

**Comment by angerman** [comment]
Sorry to hear that. It seems like you did not build from the `my-ghc` branch. That is currently an unfortunate necessity. GHC should not know about OSAndroid anymore. As for all things that GHC is concerned about Android is equivalent to Linux and iOS is equivalent to macOS, the special handling of OSAndroid and OSiOS was removed in [D3579](https://phabricator.haskell.org/D3579), which should be part of `my-ghc`.

**Comment by yihuang** [comment]
@angerman I've re-run the whole thing on your branch, still got this link error "-pie and -r are incompatible" Do you know where went wrong?

**Comment by angerman** [comment]
This looks a lot like [the issue someone else encountered with gnu step and the ndk-r10e](https://lists.gnu.org/archive/html/discuss-gnustep/2015-09/msg00050.html). What does
your `armv7-linux-androideabi-ld --version` report? If it's not gold, we might need to force it.

May I ask why you use the r10e ndk and not a more recent one?

**Comment by yihuang** [comment]
r10e is just the version I currently have, i'll try a recent one and see.
by the way, the ``armv7-linux-androideabi-ld --version `` reports:
```
GNU gold (GNU Binutils 2.24.90) 1.11
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by yihuang** [comment]
I succeeded with r14b, thanks for your work.

**Comment by angerman** [comment]
Great to know! Thanks for reporting.
