### ISSUE TITLE
"Cannot find system libffi" error

### ISSUE THREAD

**Issue by andrevdm** [zw3rk/ghc#2]
(More detail from reddit post)

I'm unable to build this version of ghc for two reasons
1. The hoopl submodule link is getting a 404. I changed it to https://github.com/haskell/hoopl.git. 
1. When building I get an error saying `Cannot find system libffi`

**System**
1. arch linux
1. I'm using stack not cabal. I'm using the ghc binary found by running `stack exec -- which ghc`

**Details**
As far as I can see I'm using the correct libffi path. For completeness here are the commands I run

_To build libffi_

>CC="/home/xxx/raspbian-sdk/prebuilt/bin/arm-linux-gnueabihf-clang" CXX="/home/xxx/raspbian-sdk/prebuilt/bin/arm-linux-gnueabihf-clang" \
>        ./configure \
>        --prefix=/home/xxx/raspbian-sdk/libffi/libffi_build \
>        --host=arm-linux-gnueabihf \
>        --enable-static=yes --enable-shared=yes
>
>make && make install

_To build ghc_
> export RASPBIAN_SDK=/home/xxx/raspbian-sdk/
> export LIBFFI=/home/xxx/raspbian-sdk/libffi/libffi_build
> ./boot
> ./configure --target=arm-linux-gnueabihf \
>             --prefix=$RASPBIAN_SDK/prebuilt \
>             --with-system-libffi \
>             --with-ffi-includes=$LIBFFI/include \
>             --with-ffi-libraries=$LIBFFI/lib \
> 	    --with-ghc=/home/xxx/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc

This fails with the error

**configure: error: Cannot find system libffi**

_The libffi output looks fine (/home/xxx/raspbian-sdk/libffi/libffi_build)_

> ../libffi/libffi_build
> +-- include
> |   +-- ffi.h
> |   +-- ffitarget.h
> +-- lib
> |   +-- libffi.a
> |   +-- libffi.la
> |   +-- libffi.so -> libffi.so.7.1.0
> |   +-- libffi.so.7 -> libffi.so.7.1.0
> |   +-- libffi.so.7.1.0
> |   +-- pkgconfig
> |       +-- libffi.pc
> +-- share
>     +-- info
>     |   +-- dir
>     |   +-- libffi.info
>     +-- man
>         +-- man3
>             +-- ffi.3
>             +-- ffi_call.3
>             +-- ffi_prep_cif.3
>             +-- ffi_prep_cif_var.3

Doing a strace on _./configure_ did not help me see the problem. It looks like its searching for *libffi.so.6* and eventually finds it in the *rts* folder (twice). So it looks ok?

I've shortened `/home/xxx/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/bin` to `.../ghc-8.0.2/bin` below

> open(".../ghc-8.0.2/bin/../haskeline-0.7.3.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../terminfo-0.4.0.2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../ghc-8.0.2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../ghc-prim-0.5.0.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> #!! and *lots* of other ENOENT for .../ghc-8.0.2/bin/../libffi.so.6
> 
> open(".../ghc-8.0.2/bin/../rts/libffi.so.6", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/bin/../lib/../lib/tls/x86_64/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/bin/../lib/../lib/tls/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/bin/../lib/../lib/x86_64/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/bin/../lib/../lib/libffi.so.6", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/bin/../lib/../lib/tls/x86_64/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/bin/../lib/../lib/tls/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/bin/../lib/../lib/x86_64/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/bin/../lib/../lib/libffi.so.6", O_RDONLY|O_CLOEXEC) = 3
> open("/usr/lib/../lib/tls/x86_64/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/lib/../lib/tls/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/lib/../lib/x86_64/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open("/usr/lib/../lib/libffi.so.6", O_RDONLY|O_CLOEXEC) = 11
> open(".../ghc-8.0.2/bin/../terminfo-0.4.0.2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../ghc-boot-8.0.2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../ghc-boot-th-8.0.2/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../Cabal-1.24.2.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../process-1.4.3.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../pretty-1.1.3.3/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../directory-1.3.0.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../unix-2.7.2.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../time-1.6.0.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../filepath-1.4.1.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../binary-0.8.3.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../containers-0.5.7.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../bytestring-0.10.8.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../deepseq-1.4.2.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../array-0.5.1.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../base-4.9.1.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../integer-gmp-1.0.0.1/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../ghc-prim-0.5.0.0/libffi.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> open(".../ghc-8.0.2/bin/../rts/libffi.so.6", O_RDONLY|O_CLOEXEC) = 3

Thanks.

**Comment by andrevdm** [comment]
I suppose it is possible that this is because I'm using slack and not cabal to install. I'll try test on a clean VM to confirm

**Comment by andrevdm** [comment]
Oh no... It may be because of a typo in the path to raspbian-sdk/prebuilt/bin 2 steps before this. :(  Confirming

**Comment by andrevdm** [comment]
Sorry for that, it was a typo in my path to the prebuilt/bin

So the only things I had to do differently were
1. Use stack not cabal
1. Get ghc path by running `stack exec -- which ghc`
1. Ignore libffi build errors (-print-multi-os-directory and no input files)
1. Change hoopl submodule link to https://github.com/haskell/hoopl.git.
1. Make sure that the correct raspbian-sdk/prebuilt/bin is in the path :+1 :'(

**Comment by angerman** [comment]
Good to know! That `hoopl` missing repo, is still kind of strange.
